# Generated by Django 3.0.5 on 2020-06-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carriage',
            old_name='ClassId',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='carriage',
            old_name='TrainId',
            new_name='Train',
        ),
        migrations.RenameField(
            model_name='departure',
            old_name='LineId',
            new_name='Line',
        ),
        migrations.RenameField(
            model_name='departure',
            old_name='TrainId',
            new_name='Train',
        ),
        migrations.RenameField(
            model_name='lineplatform',
            old_name='LineId',
            new_name='Line',
        ),
        migrations.RenameField(
            model_name='lineplatform',
            old_name='PlatformId',
            new_name='Platform',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='DiscountId',
            new_name='Discount',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='SeatId',
            new_name='Seat',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='TicketId',
            new_name='Ticket',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='CarriageId',
            new_name='Carriage',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='SeatPosId',
            new_name='SeatPos',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='DepartureId',
            new_name='Departure',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='DestinationId',
            new_name='Destination',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='PlatformId',
            new_name='StartPlatform',
        ),
        migrations.RenameField(
            model_name='trainline',
            old_name='LineId',
            new_name='Line',
        ),
        migrations.RenameField(
            model_name='trainline',
            old_name='TrainId',
            new_name='Train',
        ),
    ]
