# Generated by Django 3.0.5 on 2020-06-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainsapp', '0002_auto_20200616_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='StationId',
            new_name='Station',
        ),
    ]
