# Generated by Django 3.0.5 on 2020-06-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainsapp', '0003_auto_20200616_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='SeatPos',
        ),
        migrations.DeleteModel(
            name='SeatPos',
        ),
    ]
