# Generated by Django 3.0.5 on 2020-07-12 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainsapp', '0006_auto_20200620_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriage',
            name='Train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carriages', to='trainsapp.Train'),
        ),
        migrations.DeleteModel(
            name='TrainLine',
        ),
    ]
