# Generated by Django 3.0.5 on 2020-07-17 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainsapp', '0007_auto_20200712_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Date',
            new_name='Day',
        ),
        migrations.AlterField(
            model_name='carriage',
            name='Train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainsapp.Train'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='trainsapp.LinePlatform'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='StartPlatform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainsapp.LinePlatform'),
        ),
    ]
