# Generated by Django 3.0.5 on 2020-07-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainsapp', '0008_auto_20200717_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Price',
            field=models.FloatField(),
        ),
    ]
